import type { Metadata } from 'next';
import ReactQueryProviders from '@/lib/utils/reactQueryProvider';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="min-h-screen bg-gray-100 px-4 md:px-6 lg:px-10">
        <ReactQueryProviders>
          <main className="mx-auto min-h-screen max-w-[1200px] bg-gray-50">
            {children}
          </main>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
