import type { Metadata } from 'next';
import ReactQueryProviders from '@/lib/utils/reactQueryProvider';
import HeaderBar from '@/components/header/HeaderBar';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderBar />
        <ReactQueryProviders>{children}</ReactQueryProviders>
      </body>
    </html>
  );
}
