import { BookClub } from '@/types/bookclubs';
import { Review } from '@/types/review';
import { User } from '@/types/user';

export const mockBookClubs: BookClub[] = [
  {
    id: 1,
    title: '문학 애호가들의 모임',
    description: '문학 작품을 읽고 함께 토론하는 시간을 가져보세요.',
    meetingType: 'OFFLINE',
    bookClubType: 'FREE',
    targetDate: '2024-01-15',
    endDate: '2024-01-10',
    memberLimit: 10,
    town: '서울시 강남구',
    memberCount: 7,
    isLiked: true,
    isInactive: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'pending',
    reviewScore: 4.5,
  },
  {
    id: 2,
    title: 'SF 소설 독서회',
    description: '미래를 상상하며 SF 소설을 읽고 함께 이야기 나눠요.',
    meetingType: 'ONLINE',
    bookClubType: 'FIXED',
    targetDate: '2024-01-20',
    endDate: '2024-01-18',
    memberLimit: 15,
    town: null,
    memberCount: 12,
    isLiked: false,
    isInactive: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'confirmed',
    reviewScore: 4.8,
  },
  {
    id: 3,
    title: '역사 이야기 모임',
    description: '역사 속 인물과 사건을 주제로 깊이 있는 대화를 나눕니다.',
    meetingType: 'OFFLINE',
    bookClubType: 'FREE',
    targetDate: '2024-01-25',
    endDate: '2024-01-22',
    memberLimit: 8,
    town: '부산시 해운대구',
    memberCount: 8,
    isLiked: true,
    isInactive: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'confirmed',
    reviewScore: 4.2,
  },
  {
    id: 4,
    title: '심리학 독서 모임',
    description: '심리학 책을 통해 자기 이해와 성장에 대해 배우는 시간.',
    meetingType: 'ONLINE',
    bookClubType: 'FIXED',
    targetDate: '2024-02-10',
    endDate: '2024-02-05',
    memberLimit: 20,
    town: null,
    memberCount: 18,
    isLiked: false,
    isInactive: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'pending',
    reviewScore: 4.7,
  },
  {
    id: 5,
    title: '창작 작가들의 모임',
    description: '글쓰기와 창작 활동을 좋아하는 분들을 위한 모임.',
    meetingType: 'OFFLINE',
    bookClubType: 'FREE',
    targetDate: '2024-01-30',
    endDate: '2024-01-25',
    memberLimit: 12,
    town: '대전시 중구',
    memberCount: 10,
    isLiked: true,
    isInactive: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'pending',
    reviewScore: 4.3,
  },
  {
    id: 6,
    title: '논픽션 독서 모임',
    description: '다양한 논픽션 작품을 읽고 삶에 대해 깊이 고민해 봅니다.',
    meetingType: 'ONLINE',
    bookClubType: 'FIXED',
    targetDate: '2024-02-15',
    endDate: '2024-02-10',
    memberLimit: 25,
    town: null,
    memberCount: 23,
    isLiked: false,
    isInactive: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'confirmed',
    reviewScore: 4.9,
  },
  {
    id: 7,
    title: '철학 토론 독서회',
    description: '철학 책을 읽고 함께 깊이 있는 토론을 나눕니다.',
    meetingType: 'OFFLINE',
    bookClubType: 'FREE',
    targetDate: '2024-02-05',
    endDate: '2024-01-30',
    memberLimit: 10,
    town: '인천시 연수구',
    memberCount: 9,
    isLiked: true,
    isInactive: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'pending',
    reviewScore: 4.4,
  },
  {
    id: 8,
    title: '과학 독서 모임',
    description: '과학책을 통해 지식의 즐거움을 나누는 모임.',
    meetingType: 'ONLINE',
    bookClubType: 'FIXED',
    targetDate: '2024-01-28',
    endDate: '2024-01-25',
    memberLimit: 30,
    town: null,
    memberCount: 27,
    isLiked: false,
    isInactive: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'confirmed',
    reviewScore: 4.6,
  },
  {
    id: 9,
    title: '여행 에세이 독서회',
    description: '다양한 여행 에세이를 통해 힐링을 느껴보세요.',
    meetingType: 'OFFLINE',
    bookClubType: 'FREE',
    targetDate: '2024-01-18',
    endDate: '2024-01-15',
    memberLimit: 15,
    town: '제주시 애월읍',
    memberCount: 14,
    isLiked: true,
    isInactive: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'pending',
    reviewScore: 4.1,
  },
  {
    id: 10,
    title: '예술과 인문학 독서회',
    description: '예술과 인문학을 결합한 독서와 토론의 시간.',
    meetingType: 'ONLINE',
    bookClubType: 'FIXED',
    targetDate: '2024-02-01',
    endDate: '2024-01-28',
    memberLimit: 18,
    town: null,
    memberCount: 16,
    isLiked: false,
    isInactive: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'pending',
    reviewScore: 4.5,
  },
];

export const mockReviews: Review[] = [
  {
    id: 1,
    userId: 101,
    bookClubId: 201,
    rating: 4,
    content: '정말 유익한 독서 모임이었어요! 다음에도 꼭 참여하고 싶어요.',
    image: '/images/defaultBookClub.jpg',
    createdAt: '2024-12-30T10:00:00Z',
    profileImg: 'https://example.com/profile1.jpg',
    userName: '김영희',
    clubName: '문학 애호가 모임',
    bookClubType: 'FREE',
  },
  {
    id: 2,
    userId: 102,
    bookClubId: 202,
    rating: 5,
    content: '매주 깊이 있는 토론이 있어서 정말 좋아요!',
    image: '/images/defaultBookClub.jpg',
    createdAt: '2024-12-29T14:30:00Z',
    profileImg: 'https://example.com/profile2.jpg',
    userName: '박철수',
    clubName: '책 사랑 모임',
    bookClubType: 'FIXED',
  },
  {
    id: 3,
    userId: 103,
    bookClubId: 203,
    rating: 3,
    content: '전체적으로 괜찮았지만 조금 더 체계적이면 좋을 것 같아요.',
    image: '/images/defaultBookClub.jpg',
    createdAt: '2024-12-28T16:45:00Z',
    profileImg: 'https://example.com/profile3.jpg',
    userName: '이민수',
    clubName: '편안한 독서회',
    bookClubType: 'FREE',
  },
  {
    id: 4,
    userId: 104,
    bookClubId: 204,
    rating: 5,
    content: '참가자들이 너무 친절하고 분위기가 좋았어요!',
    image: '/images/defaultBookClub.jpg',
    createdAt: '2024-12-27T12:20:00Z',
    profileImg: 'https://example.com/profile4.jpg',
    userName: '최수진',
    clubName: '독서의 안식처',
    bookClubType: 'FIXED',
  },
  {
    id: 5,
    userId: 105,
    bookClubId: 205,
    rating: 2,
    content: '제가 기대했던 것과는 조금 달라 아쉬웠어요.',
    image: '/images/defaultBookClub.jpg',
    createdAt: '2024-12-26T09:15:00Z',
    profileImg: 'https://example.com/profile5.jpg',
    userName: '정은우',
    clubName: '소설 애호가들',
    bookClubType: 'FREE',
  },
  {
    id: 6,
    userId: 106,
    bookClubId: 206,
    rating: 4,
    content: '이번 달의 책 선정이 정말 마음에 들었어요!',
    image: '/images/defaultBookClub.jpg',
    createdAt: '2024-12-25T18:05:00Z',
    profileImg: 'https://example.com/profile6.jpg',
    userName: '김서연',
    clubName: '논픽션 마니아',
    bookClubType: 'FIXED',
  },
  {
    id: 7,
    userId: 107,
    bookClubId: 207,
    rating: 5,
    content: '일상에서 벗어나 독서를 즐길 수 있는 멋진 시간이었어요.',
    image: '/images/defaultBookClub.jpg',
    createdAt: '2024-12-24T20:00:00Z',
    profileImg: 'https://example.com/profile7.jpg',
    userName: '박지훈',
    clubName: 'SF 독서 모임',
    bookClubType: 'FREE',
  },
  {
    id: 8,
    userId: 108,
    bookClubId: 208,
    rating: 4,
    content: '다양한 의견을 들을 수 있어서 좋았어요.',
    image: '/images/defaultBookClub.jpg',
    createdAt: '2024-12-23T11:10:00Z',
    profileImg: 'https://example.com/profile8.jpg',
    userName: '한유진',
    clubName: '철학 독서회',
    bookClubType: 'FIXED',
  },
  {
    id: 9,
    userId: 109,
    bookClubId: 209,
    rating: 3,
    content: '재미있었지만 시간이 너무 짧아서 아쉬웠어요.',
    image: '/images/defaultBookClub.jpg',
    createdAt: '2024-12-22T15:45:00Z',
    profileImg: 'https://example.com/profile9.jpg',
    userName: '이준호',
    clubName: '역사 독서 모임',
    bookClubType: 'FREE',
  },
  {
    id: 10,
    userId: 110,
    bookClubId: 210,
    rating: 5,
    content: '참가자들과 교류하면서 많은 영감을 얻었어요!',
    image: '/images/defaultBookClub.jpg',
    createdAt: '2024-12-21T08:30:00Z',
    profileImg: 'https://example.com/profile10.jpg',
    userName: '김하늘',
    clubName: '창작 작가 모임',
    bookClubType: 'FIXED',
  },
];

export const mockUser: User = {
  id: 1,
  name: 'John Doe',
  nickname: 'Johnny',
  email: 'john.doe@example.com',
  description: 'A software developer.',
  image: '',
  createdAt: '2024-12-30T05:37:19.084Z',
  updatedAt: '2024-12-30T05:37:19.084Z',
};
