import { BookClub } from '../types';

export const mockJoinedBookClubList: BookClub[] = [
  {
    clubId: 1,
    title: '문학의 밤',
    description: '고전 문학을 주제로 이야기하는 모임입니다.',
    meetingType: 'OFFLINE',
    bookClubType: 'FIXED',
    targetDate: '2024-01-20T18:00:00Z',
    endDate: '2024-01-18T23:59:59Z',
    memberLimit: 15,
    town: '서울 종로구',
    memberCount: 12,
    isLiked: false,
    isCanceled: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'pending',
    reviewScore: 4.7,
  },
  {
    clubId: 2,
    title: '철학과 삶',
    description: '자유롭게 철학적 주제를 다루는 독서 모임입니다.',
    meetingType: 'ONLINE',
    bookClubType: 'FREE',
    targetDate: '2024-02-10T20:00:00Z',
    endDate: '2024-02-05T23:59:59Z',
    memberLimit: 10,
    town: '',
    memberCount: 8,
    isLiked: true,
    isCanceled: false,
    imageUrl: undefined,
    isPast: false,
    clubStatus: 'pending',
    reviewScore: undefined,
  },
  {
    clubId: 3,
    title: '추리소설 탐독',
    description: '추리 소설 애호가를 위한 독서 모임입니다.',
    meetingType: 'OFFLINE',
    bookClubType: 'FIXED',
    targetDate: '2024-01-25T19:30:00Z',
    endDate: '2024-01-20T23:59:59Z',
    memberLimit: 12,
    town: '서울 마포구',
    memberCount: 12,
    isLiked: true,
    isCanceled: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: true,
    clubStatus: 'confirmed',
    reviewScore: 4.8,
  },
  {
    clubId: 4,
    title: 'SF소설의 미래',
    description: '과학 소설의 미래를 탐구하는 책 모임입니다.',
    meetingType: 'ONLINE',
    bookClubType: 'FREE',
    targetDate: '2024-03-05T19:00:00Z',
    endDate: '2024-03-01T23:59:59Z',
    memberLimit: 20,
    town: '',
    memberCount: 5,
    isLiked: false,
    isCanceled: false,
    imageUrl: undefined,
    isPast: false,
    clubStatus: 'pending',
    reviewScore: undefined,
  },
  {
    clubId: 5,
    title: '시의 세계',
    description: '자작 시와 유명 시를 낭독하고 교감하는 모임입니다.',
    meetingType: 'OFFLINE',
    bookClubType: 'FREE',
    targetDate: '2024-02-14T18:30:00Z',
    endDate: '2024-02-10T23:59:59Z',
    memberLimit: 10,
    town: '부산 해운대구',
    memberCount: 6,
    isLiked: false,
    isCanceled: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'pending',
    reviewScore: 4.0,
  },
  {
    clubId: 6,
    title: '경제와 사회',
    description: '현대 경제학의 주요 이슈를 토론하는 독서 모임입니다.',
    meetingType: 'ONLINE',
    bookClubType: 'FIXED',
    targetDate: '2024-02-01T20:00:00Z',
    endDate: '2024-01-28T23:59:59Z',
    memberLimit: 8,
    town: '',
    memberCount: 8,
    isLiked: true,
    isCanceled: false,
    imageUrl: undefined,
    isPast: true,
    clubStatus: 'confirmed',
    reviewScore: 3.5,
  },
  {
    clubId: 7,
    title: '청소년 문학 클럽',
    description: '청소년 소설을 중심으로 토론하는 독서 모임입니다.',
    meetingType: 'OFFLINE',
    bookClubType: 'FIXED',
    targetDate: '2024-02-20T17:00:00Z',
    endDate: '2024-02-18T23:59:59Z',
    memberLimit: 12,
    town: '대구 중구',
    memberCount: 7,
    isLiked: true,
    isCanceled: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'pending',
    reviewScore: 4.2,
  },
  {
    clubId: 8,
    title: '현대 미술과 문학',
    description: '현대 미술과 문학의 교차점을 탐구하는 모임입니다.',
    meetingType: 'ONLINE',
    bookClubType: 'FREE',
    targetDate: '2024-01-30T19:00:00Z',
    endDate: '2024-01-25T23:59:59Z',
    memberLimit: 15,
    town: '',
    memberCount: 10,
    isLiked: false,
    isCanceled: false,
    imageUrl: undefined,
    isPast: true,
    clubStatus: 'pending',
    reviewScore: 4.3,
  },
  {
    clubId: 9,
    title: '영화와 책',
    description: '영화 원작 소설을 읽고 영화와 비교하는 독서 모임입니다.',
    meetingType: 'OFFLINE',
    bookClubType: 'FIXED',
    targetDate: '2024-02-07T18:00:00Z',
    endDate: '2024-02-03T23:59:59Z',
    memberLimit: 10,
    town: '서울 용산구',
    memberCount: 10,
    isLiked: true,
    isCanceled: false,
    imageUrl: '/images/defaultBookClub.jpg',
    isPast: false,
    clubStatus: 'confirmed',
    reviewScore: 4.9,
  },
  {
    clubId: 10,
    title: '환상 문학의 향연',
    description: '판타지 소설을 좋아하는 사람들을 위한 모임입니다.',
    meetingType: 'ONLINE',
    bookClubType: 'FREE',
    targetDate: '2024-01-22T20:00:00Z',
    endDate: '2024-01-20T23:59:59Z',
    memberLimit: 15,
    town: '',
    memberCount: 15,
    isLiked: false,
    isCanceled: false,
    imageUrl: undefined,
    isPast: true,
    clubStatus: 'closed',
    reviewScore: 5.0,
  },
  {
    clubId: 11,
    title: '역사와 문학',
    description: '역사적 사건과 문학 작품을 연결하여 토론하는 모임입니다.',
    meetingType: 'ONLINE',
    bookClubType: 'FREE',
    targetDate: '2023-12-01T19:00:00Z',
    endDate: '2023-11-28T23:59:59Z',
    memberLimit: 10,
    town: '',
    memberCount: 7,
    isLiked: false,
    isCanceled: false,
    imageUrl: undefined,
    isPast: true,
    clubStatus: 'closed',
    reviewScore: undefined,
  },
];
